var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/agents/business-intelligence/route.js")
R.c("server/chunks/src_agents_0m6xua1._.js")
R.c("server/chunks/src_lib_llm-router_ts_0jwpa_1._.js")
R.c("server/chunks/src_agents_core_orchestrator_ts_12r041n._.js")
R.c("server/chunks/src_lib_telegram_ts_0junhbg._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__0jywc6b._.js")
R.c("server/chunks/_next-internal_server_app_api_agents_business-intelligence_route_actions_0-25-1z.js")
R.m(322089)
module.exports=R.m(322089).exports
