var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/google-ads/performance/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/[root-of-the-server]__05micv1._.js")
R.c("server/chunks/src_lib_google-ads_ts_0.q68yh._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/src_lib_auth_ts_12a23vj._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_google-ads_performance_route_actions_0etv2vm.js")
R.m(429301)
module.exports=R.m(429301).exports
