var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/meta-catalog/config/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/[root-of-the-server]__0.1b50r._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/src_lib_auth_ts_12a23vj._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_meta-catalog_config_route_actions_0pvsve3.js")
R.m(651879)
module.exports=R.m(651879).exports
