var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/ai/chat/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/src_lib_copywriting-frameworks_ts_10u2s.h._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/src_lib_llm-router_ts_0jwpa_1._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__0lhgx_t._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/src_lib_auth_ts_12a23vj._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/src_lib_openai-ads_ts_0no-0yr._.js")
R.c("server/chunks/src_lib_services-catalog_ts_0fssx_i._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_ai_chat_route_actions_0vtdtth.js")
R.m(248605)
module.exports=R.m(248605).exports
