var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/locksmiths/send-base-location-sms/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/src_lib_sms_ts_0_4nb2m._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__071q_ea._.js")
R.c("server/chunks/src_lib_auth_ts_12a23vj._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/0zjb_server_app_api_admin_locksmiths_send-base-location-sms_route_actions_0xms0p6.js")
R.m(507002)
module.exports=R.m(507002).exports
