var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/company/members/[memberId]/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/[root-of-the-server]__0zbmzvz._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_company_members_[memberId]_route_actions_0h6bm93.js")
R.m(81466)
module.exports=R.m(81466).exports
