var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/locksmiths/send-app-install-reminder/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/[root-of-the-server]__11wopl0._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/src_lib_auth_ts_12a23vj._.js")
R.c("server/chunks/src_lib_email_ts_0kzbpfl._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/node_modules_0rdscaq._.js")
R.c("server/chunks/0zjb_server_app_api_admin_locksmiths_send-app-install-reminder_route_actions_0x~xydy.js")
R.m(209410)
module.exports=R.m(209410).exports
