var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/register/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/src_lib_telegram_ts_0junhbg._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/src_lib_auth_ts_12a23vj._.js")
R.c("server/chunks/[root-of-the-server]__0e~wmmn._.js")
R.c("server/chunks/src_lib_email_ts_0kzbpfl._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_0rdscaq._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_register_route_actions_096_y_i.js")
R.m(606706)
module.exports=R.m(606706).exports
