// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accessibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accessibility">> = Specific
  const handler = {} as typeof import("../../src/app/accessibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads/assistant">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/audiences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads/audiences">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/audiences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads/docs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads/setup">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ads/utm-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ads/utm-builder">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ads/utm-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/agents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/agents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/agents/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents/goals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/agents/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents">> = Specific
  const handler = {} as typeof import("../../src/app/admin/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/agents/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/admin/agents/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/attribution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/attribution">> = Specific
  const handler = {} as typeof import("../../src/app/admin/attribution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/jobs/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/jobs/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/locksmiths/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/locksmiths">> = Specific
  const handler = {} as typeof import("../../src/app/admin/locksmiths/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing">> = Specific
  const handler = {} as typeof import("../../src/app/admin/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/organic/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organic/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/organic/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/organic/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organic/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/admin/organic/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/organic/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organic/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/organic/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/organic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organic">> = Specific
  const handler = {} as typeof import("../../src/app/admin/organic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/organic/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organic/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/organic/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payouts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/refunds">> = Specific
  const handler = {} as typeof import("../../src/app/admin/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/voice-receptionist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/voice-receptionist">> = Specific
  const handler = {} as typeof import("../../src/app/admin/voice-receptionist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/category/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/category/[category]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/category/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/continue-request/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/continue-request/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/continue-request/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../src/app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cooling-off/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooling-off">> = Specific
  const handler = {} as typeof import("../../src/app/cooling-off/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/customer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/job/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/job/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/customer/job/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/job/[id]/quote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/job/[id]/quote">> = Specific
  const handler = {} as typeof import("../../src/app/customer/job/[id]/quote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/job/[id]/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/job/[id]/review">> = Specific
  const handler = {} as typeof import("../../src/app/customer/job/[id]/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer">> = Specific
  const handler = {} as typeof import("../../src/app/customer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/settings">> = Specific
  const handler = {} as typeof import("../../src/app/customer/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/for-locksmiths/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/for-locksmiths">> = Specific
  const handler = {} as typeof import("../../src/app/for-locksmiths/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../src/app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/how-it-works">> = Specific
  const handler = {} as typeof import("../../src/app/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job/[id]/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job/[id]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/job/[id]/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job/[id]/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job/[id]/report">> = Specific
  const handler = {} as typeof import("../../src/app/job/[id]/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith-area/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith-area/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith-area/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith-city/[city]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith-city/[city]">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith-city/[city]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith-rickmansworth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith-rickmansworth">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith-rickmansworth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith-signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith-signup">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith-signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/earnings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/earnings">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/earnings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/faq">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/history">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/job/[id]/quote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/job/[id]/quote">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/job/[id]/quote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/job/[id]/work/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/job/[id]/work">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/job/[id]/work/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/login">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locksmith/settings">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboard/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboard/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/onboard/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/refund-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refund-policy">> = Specific
  const handler = {} as typeof import("../../src/app/refund-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/report/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/report/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/request">> = Specific
  const handler = {} as typeof import("../../src/app/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/review/[jobId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review/[jobId]">> = Specific
  const handler = {} as typeof import("../../src/app/review/[jobId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/security-checklist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-checklist">> = Specific
  const handler = {} as typeof import("../../src/app/security-checklist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vulnerable-customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vulnerable-customers">> = Specific
  const handler = {} as typeof import("../../src/app/vulnerable-customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ads/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ads/[id]/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ads/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ads/audiences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ads/audiences">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ads/audiences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ads/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ads/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ads/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ads">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ads/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ads/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ads/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ai/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/ai/generate-copy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ai/generate-copy">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/ai/generate-copy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/attribution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/attribution">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/attribution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/emails/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emails/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/emails/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/emails/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emails/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/emails/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/emails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emails">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/emails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/emails/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emails/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/emails/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/emails/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emails/track">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/emails/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/env-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/env-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/env-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/jobs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/jobs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/jobs/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/jobs/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/jobs/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/marketing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketing">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/marketing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/organic/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organic/[id]/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/organic/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/organic/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organic/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/organic/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/organic/autopilot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organic/autopilot">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/organic/autopilot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/organic/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organic/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/organic/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/organic/pillars/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organic/pillars">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/organic/pillars/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/organic/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organic">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/organic/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/payouts/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payouts/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/payouts/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payouts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/refunds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/refunds">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/refunds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/telegram/test-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/telegram/test-all">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/telegram/test-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/telegram/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/telegram/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/telegram/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/utm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/utm">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/utm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/verify-insurance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/verify-insurance">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/verify-insurance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/locksmiths/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/locksmiths">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/locksmiths/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/nlp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/nlp">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/nlp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/telegram/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/telegram">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/telegram/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/[agentId]/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/[agentId]/heartbeat">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/[agentId]/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/[agentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/[agentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/[agentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/approvals/[approvalId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/approvals/[approvalId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/approvals/[approvalId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/approvals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/approvals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/goals/[goalId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/goals/[goalId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/goals/[goalId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/goals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/goals">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/goals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/heartbeat">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/tasks/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/tasks/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bland/check-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bland/check-user">> = Specific
  const handler = {} as typeof import("../../src/app/api/bland/check-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bland/create-job/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bland/create-job">> = Specific
  const handler = {} as typeof import("../../src/app/api/bland/create-job/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bland/create-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bland/create-user">> = Specific
  const handler = {} as typeof import("../../src/app/api/bland/create-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bland/send-notification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bland/send-notification">> = Specific
  const handler = {} as typeof import("../../src/app/api/bland/send-notification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bland/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bland/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/bland/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/continue-request/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/continue-request/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/api/continue-request/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/availability-schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/availability-schedule">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/availability-schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/generate-organic/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/generate-organic">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/generate-organic/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/generate-payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/generate-payouts">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/generate-payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/insurance-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/insurance-reminders">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/insurance-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/publish-organic/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/publish-organic">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/publish-organic/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/signature-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/signature-reminders">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/signature-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/sync-meta-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sync-meta-performance">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/sync-meta-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/accept-terms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/accept-terms">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/accept-terms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/onboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/onboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/onboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/accept-application/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/accept-application">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/accept-application/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/applications">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/cancel-refund/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/cancel-refund">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/cancel-refund/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/confirm-completion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/confirm-completion">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/confirm-completion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/photos/[photoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/photos/[photoId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/photos/[photoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/photos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/photos">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/photos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/quote">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/signature/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/signature">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/signature/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmith/accept-terms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmith/accept-terms">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmith/accept-terms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmith/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmith/applications">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmith/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmith/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmith/availability">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmith/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmith/availability/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmith/availability/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmith/availability/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmith/bot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmith/bot">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmith/bot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmith/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmith/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmith/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmith/update-insurance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmith/update-insurance">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmith/update-insurance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmiths/[id]/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmiths/[id]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmiths/[id]/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmiths/[id]/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmiths/[id]/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmiths/[id]/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmiths/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmiths/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmiths/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmiths/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmiths/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmiths/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmiths/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmiths/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmiths/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locksmiths/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locksmiths">> = Specific
  const handler = {} as typeof import("../../src/app/api/locksmiths/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketing/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing/leads">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketing/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketing/modals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing/modals">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketing/modals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketing/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketing/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketing/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketing/track">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketing/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/[id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]/read">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/[id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/broadcast">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/read-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/read-all">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/read-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/unsubscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onesignal/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onesignal/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/onesignal/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onesignal/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onesignal/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/onesignal/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onesignal/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onesignal/unsubscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/onesignal/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/charge-saved-card/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/charge-saved-card">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/charge-saved-card/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/create-intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/create-intent">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/create-intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/saved-cards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/saved-cards">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/saved-cards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/setup-card/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/setup-card">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/setup-card/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/retell/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retell/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/retell/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/retell/calls/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retell/calls/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/retell/calls/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/retell/calls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retell/calls">> = Specific
  const handler = {} as typeof import("../../src/app/api/retell/calls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/retell/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retell/config">> = Specific
  const handler = {} as typeof import("../../src/app/api/retell/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/retell/test-call/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retell/test-call">> = Specific
  const handler = {} as typeof import("../../src/app/api/retell/test-call/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/retell/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retell/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/retell/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatures">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe-connect/onboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe-connect/onboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe-connect/onboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe-connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe-connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe-connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/test-sms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-sms">> = Specific
  const handler = {} as typeof import("../../src/app/api/test-sms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tracking/conversions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracking/conversions">> = Specific
  const handler = {} as typeof import("../../src/app/api/tracking/conversions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tracking/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracking/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/tracking/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/meta">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/resend">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/attribution/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/attribution">> = Specific
  const handler = {} as typeof import("../../src/app/admin/attribution/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cookies/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../src/app/cookies/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/customer/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/job/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer/job">> = Specific
  const handler = {} as typeof import("../../src/app/customer/job/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer">> = Specific
  const handler = {} as typeof import("../../src/app/customer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer/settings">> = Specific
  const handler = {} as typeof import("../../src/app/customer/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/help/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/help">> = Specific
  const handler = {} as typeof import("../../src/app/help/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/job">> = Specific
  const handler = {} as typeof import("../../src/app/job/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith-rickmansworth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith-rickmansworth">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith-rickmansworth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith-signup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith-signup">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith-signup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/earnings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/earnings">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/earnings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/faq/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/faq">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/faq/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/history/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/history">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/history/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/job/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/job">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/job/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/jobs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/jobs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/login">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/locksmith/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/locksmith/settings">> = Specific
  const handler = {} as typeof import("../../src/app/locksmith/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/refund-policy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/refund-policy">> = Specific
  const handler = {} as typeof import("../../src/app/refund-policy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/report/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/report">> = Specific
  const handler = {} as typeof import("../../src/app/report/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/request/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/request">> = Specific
  const handler = {} as typeof import("../../src/app/request/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/review/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/review">> = Specific
  const handler = {} as typeof import("../../src/app/review/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/security-checklist/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/security-checklist">> = Specific
  const handler = {} as typeof import("../../src/app/security-checklist/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-email/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/verify-email/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
