var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/advance-auctions/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/src_lib_telegram_ts_0junhbg._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__0nmdiz-._.js")
R.c("server/chunks/src_lib_native-push_ts_0m_bb1x._.js")
R.c("server/chunks/[root-of-the-server]__0hyd_8a._.js")
R.c("server/chunks/[root-of-the-server]__0l8z3mh._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_next-internal_server_app_api_cron_advance-auctions_route_actions_003kxv7.js")
R.m(304460)
module.exports=R.m(304460).exports
