var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/locksmith/update-dbs/route.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/src_lib_telegram_ts_0junhbg._.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/src_lib_llm-router_ts_0jwpa_1._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__0alqcba._.js")
R.c("server/chunks/_next-internal_server_app_api_locksmith_update-dbs_route_actions_0_q~x6r.js")
R.m(45531)
module.exports=R.m(45531).exports
