var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/ads/import/route.js")
R.c("server/chunks/[root-of-the-server]__0o6sfw_._.js")
R.c("server/chunks/[root-of-the-server]__0yxc~i0._.js")
R.c("server/chunks/src_lib_meta-marketing_ts_0it-36b._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0~rhsvv.js")
R.c("server/chunks/node_modules_next_124cnn1._.js")
R.c("server/chunks/src_lib_auth_ts_12a23vj._.js")
R.c("server/chunks/node_modules_0iyr.47._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_ads_import_route_actions_01mum0c.js")
R.m(211488)
module.exports=R.m(211488).exports
