var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/insurance-reminders/route.js")
R.c("server/chunks/[root-of-the-server]__0-cdnm0._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_0rdscaq._.js")
R.c("server/chunks/[root-of-the-server]__0945oel._.js")
R.c("server/chunks/src_lib_email_ts_0kzbpfl._.js")
R.c("server/chunks/_next-internal_server_app_api_cron_insurance-reminders_route_actions_12_ujne.js")
R.m(27368)
module.exports=R.m(27368).exports
